const multiplicacion = 10 * 5;
console.log(multiplicacion);
const division = 10 / 2;
console.log(division);
const resto = 15 % 9;
console.log(resto);
const p = 10;
const j = 5;
let o = p + j;
console.log(o);
const c = 10;
const m = 5;
let i = c * m;
console.log(i);